/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.time.LocalDate;
import java.util.Date;
import java.util.Locale;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Employee;
import model.EmployeeHistory;

/**
 *
 * @author chaitanya
 */
public class CreateEmployeeDetails extends javax.swing.JPanel {

    /**
     * Creates new form CreateEmployeeDetails
     */
    EmployeeHistory history;
   
    public CreateEmployeeDetails(EmployeeHistory history) {
        initComponents();
        this.history = history;
        

        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        LabelEmpID = new javax.swing.JLabel();
        LabelAge = new javax.swing.JLabel();
        LabelGender = new javax.swing.JLabel();
        LabelStDate = new javax.swing.JLabel();
        LabelLevel = new javax.swing.JLabel();
        LabelTeamInfo = new javax.swing.JLabel();
        LabelPoTitle = new javax.swing.JLabel();
        LabelNumber = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        FieldName = new javax.swing.JTextField();
        FieldEmpId = new javax.swing.JTextField();
        FieldAge = new javax.swing.JTextField();
        FieldGender = new javax.swing.JTextField();
        FieldStDate = new javax.swing.JTextField();
        FieldLevel = new javax.swing.JTextField();
        FieldTeamInfo = new javax.swing.JTextField();
        FieldPosTitle = new javax.swing.JTextField();
        FieldNumber = new javax.swing.JTextField();
        FieldEmail = new javax.swing.JTextField();
        ButtonCreate = new javax.swing.JButton();
        txtPhoto = new javax.swing.JLabel();
        PhotoBtn = new javax.swing.JButton();
        LabelPhoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jFileChooser1.setMaximumSize(new java.awt.Dimension(10, 10));
        jFileChooser1.setMinimumSize(new java.awt.Dimension(5, 5));

        setBackground(new java.awt.Color(230, 165, 25));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("CREATE EMPLOYEE RECORD");

        LabelName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LabelName.setText("Name:");

        LabelEmpID.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LabelEmpID.setText("Employee ID:");

        LabelAge.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LabelAge.setText("Age:");

        LabelGender.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LabelGender.setText("Gender:");

        LabelStDate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LabelStDate.setText("Start Date:");

        LabelLevel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LabelLevel.setText("Level:");

        LabelTeamInfo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LabelTeamInfo.setText("Team Information:");

        LabelPoTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LabelPoTitle.setText("Position Title:");

        LabelNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LabelNumber.setText("Cell Phone Number:");

        LabelEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LabelEmail.setText("Email Address:");

        FieldName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FieldName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        FieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNameActionPerformed(evt);
            }
        });

        FieldEmpId.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FieldEmpId.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));

        FieldAge.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FieldAge.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        FieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldAgeActionPerformed(evt);
            }
        });

        FieldGender.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FieldGender.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));

        FieldStDate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FieldStDate.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));

        FieldLevel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FieldLevel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));

        FieldTeamInfo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FieldTeamInfo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));

        FieldPosTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FieldPosTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));

        FieldNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FieldNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        FieldNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNumberActionPerformed(evt);
            }
        });

        FieldEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FieldEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        FieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldEmailActionPerformed(evt);
            }
        });

        ButtonCreate.setText("Create");
        ButtonCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        ButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreateActionPerformed(evt);
            }
        });

        txtPhoto.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtPhoto.setText("Photo:");

        PhotoBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        PhotoBtn.setText("Upload");
        PhotoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotoBtnActionPerformed(evt);
            }
        });

        LabelPhoto.setBackground(new java.awt.Color(0, 153, 204));
        LabelPhoto.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LabelPhoto.setForeground(new java.awt.Color(0, 153, 204));
        LabelPhoto.setBounds(new java.awt.Rectangle(50, 50, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/chaitanya/Desktop/admin2.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/chaitanya/Desktop/admin2.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LabelNumber)
                                        .addComponent(LabelEmpID)
                                        .addComponent(LabelName)
                                        .addComponent(LabelStDate)
                                        .addComponent(LabelLevel)
                                        .addComponent(LabelPoTitle)
                                        .addComponent(LabelGender)
                                        .addComponent(LabelEmail)
                                        .addComponent(LabelTeamInfo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addComponent(txtPhoto))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(339, 339, 339)
                                .addComponent(LabelAge, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldName)
                            .addComponent(FieldEmpId)
                            .addComponent(FieldAge)
                            .addComponent(FieldGender)
                            .addComponent(FieldTeamInfo)
                            .addComponent(FieldPosTitle)
                            .addComponent(FieldNumber)
                            .addComponent(FieldLevel)
                            .addComponent(FieldStDate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(PhotoBtn))
                                    .addComponent(ButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {FieldAge, FieldEmail, FieldEmpId, FieldGender, FieldLevel, FieldName, FieldNumber, FieldPosTitle, FieldStDate, FieldTeamInfo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelName)
                    .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmpID)
                    .addComponent(FieldEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(LabelAge, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGender)
                    .addComponent(FieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldStDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelStDate))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLevel))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTeamInfo)
                    .addComponent(FieldTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPoTitle)
                    .addComponent(FieldPosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNumber)
                    .addComponent(FieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail)
                    .addComponent(FieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhotoBtn)
                            .addComponent(txtPhoto))
                        .addGap(21, 21, 21)
                        .addComponent(ButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FieldAge, FieldEmail, FieldEmpId, FieldGender, FieldLevel, FieldName, FieldNumber, FieldPosTitle, FieldStDate, FieldTeamInfo});

    }// </editor-fold>//GEN-END:initComponents

    private void FieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNameActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_FieldNameActionPerformed

    private void ButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateActionPerformed
        // TODO add your handling code here:
        
        


        String Name = FieldName.getText();
        String Employee_ID = FieldEmpId.getText();
        int Age = Integer.parseInt(FieldAge.getText());
        String Gender = FieldGender.getText();
        String Start_Date = FieldStDate.getText();
        String Level = FieldLevel.getText();
        String Team_Info = FieldTeamInfo.getText();
        String Position_Title = FieldPosTitle.getText();
        int Cell_Phone_Number = Integer.parseInt(FieldNumber.getText());
        String Email_Address = FieldEmail.getText();
        ImageIcon Photo = (ImageIcon) LabelPhoto.getIcon();
        
         
        
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", FieldEmail.getText()))) {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            }
        else if (!Pattern.matches("^\\d+$", FieldAge.getText())) 
         {
             JOptionPane.showMessageDialog(null, "Age cannot be negative", "Error", JOptionPane.ERROR_MESSAGE);
         }
        else if (!Pattern.matches("^(1[89]|[2-9]\\d)$", FieldAge.getText())) 
         {
             JOptionPane.showMessageDialog(null, "Age should be between 18 to 99", "Error", JOptionPane.ERROR_MESSAGE);
         }
        else if (!Pattern.matches("^[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2}$", FieldStDate.getText())) 
         {
             JOptionPane.showMessageDialog(null, "Please enter Valid Date. Acceptable form (dd/mm/yyyy)", "Error", JOptionPane.ERROR_MESSAGE);
         } 
        
        else if (!Pattern.matches("([A-Z][a-z]*)([\\\\s\\\\\\'-][A-Z][a-z]*)*", FieldName.getText())) 
         {
             JOptionPane.showMessageDialog(null, "Name cannot contain NUMBERS or SPECIAL CHARACTERS. Please enter a valid name", "Error", JOptionPane.ERROR_MESSAGE);
         } 
        else if (!Pattern.matches("^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", FieldNumber.getText())) 
         {
             JOptionPane.showMessageDialog(null, "Please enter 10 digit valid Phone Number.", "Error", JOptionPane.ERROR_MESSAGE);
         } 
        else {
            
            Employee e = history.addNewRecord();

            e.setName(Name);
            e.setAge(Age);
            e.setEmail_Address(Email_Address);
            e.setCell_Phone_Number(Cell_Phone_Number);
            e.setLevel(Level);
            e.setPosition_Title(Position_Title);
            e.setStart_Date(Start_Date);
            e.setTeam_Info(Team_Info);
            e.setGender(Gender);
            e.setEmployee_ID(Employee_ID);
            e.setPhoto((ImageIcon) LabelPhoto.getIcon());
        
            JOptionPane.showMessageDialog(this, "Employee Information Saved");

            FieldName.setText("");
            FieldEmpId.setText("");
            FieldAge.setText("");
            FieldGender.setText("");
            FieldStDate.setText("");
            FieldLevel.setText("");
            FieldTeamInfo.setText("");
            FieldPosTitle.setText("");
            FieldNumber.setText("");
            FieldEmail.setText("");  
            LabelPhoto.setIcon(null);

        }

         
    }//GEN-LAST:event_ButtonCreateActionPerformed

    private void PhotoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotoBtnActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Only three extensions supported","jpg","jpeg","png");
        fileChooser.setFileFilter(filter);
        int selected = fileChooser.showOpenDialog(this);
        if(selected == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            String getselectedImage = file.getAbsolutePath();
            JOptionPane.showMessageDialog(null,getselectedImage);
            ImageIcon imgIcon = new ImageIcon(getselectedImage);
            Image imgFit = imgIcon.getImage();
            Image imageFit = imgFit.getScaledInstance(LabelPhoto.getWidth(), LabelPhoto.getHeight(), Image.SCALE_SMOOTH);
            LabelPhoto.setIcon(new ImageIcon(imageFit));
            
            
            
            
        }  
        
        
    }//GEN-LAST:event_PhotoBtnActionPerformed

    private void FieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldEmailActionPerformed
        // TODO add your handling code here:
        
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", FieldEmail.getText()))) 
            {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
    }//GEN-LAST:event_FieldEmailActionPerformed

    private void FieldNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNumberActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_FieldNumberActionPerformed

    private void FieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldAgeActionPerformed
        // TODO add your handling code here:
        if (!Pattern.matches("^\\d+$", FieldAge.getText())) 
         {
             JOptionPane.showMessageDialog(null, "Age cannot be negative", "Error", JOptionPane.ERROR_MESSAGE);
         }
        else if (!Pattern.matches("^(1[89]|[2-9]\\d)$", FieldAge.getText())) 
         {
             JOptionPane.showMessageDialog(null, "Age should be between 18 to 99", "Error", JOptionPane.ERROR_MESSAGE);
         }
        
        
       

    }//GEN-LAST:event_FieldAgeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCreate;
    private javax.swing.JTextField FieldAge;
    private javax.swing.JTextField FieldEmail;
    private javax.swing.JTextField FieldEmpId;
    private javax.swing.JTextField FieldGender;
    private javax.swing.JTextField FieldLevel;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldNumber;
    private javax.swing.JTextField FieldPosTitle;
    private javax.swing.JTextField FieldStDate;
    private javax.swing.JTextField FieldTeamInfo;
    private javax.swing.JLabel LabelAge;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEmpID;
    private javax.swing.JLabel LabelGender;
    private javax.swing.JLabel LabelLevel;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelNumber;
    private javax.swing.JLabel LabelPhoto;
    private javax.swing.JLabel LabelPoTitle;
    private javax.swing.JLabel LabelStDate;
    private javax.swing.JLabel LabelTeamInfo;
    private javax.swing.JButton PhotoBtn;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel txtPhoto;
    // End of variables declaration//GEN-END:variables

    
    
    byte[] photo=null;
    String filename = null;
    
}

